version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: ecoraee_mysql
    environment:
      MYSQL_ROOT_PASSWORD: EcoRaee2026!
      MYSQL_DATABASE: EcoRaeeUac_DB
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
